export const docCategory = [
  {
    docCategory: 'HPS',
    description: 'Harga Perkiraan Sendiri',
    createdBy: '582127',
  },
  {
    docCategory: 'PA',
    description: 'Profitability Analyst',
    createdBy: '582127',
  },
  {
    docCategory: 'Other',
    description: 'Document pendukung lainnya',
    createdBy: '582127',
  },
];

export const status = [
  {
    idStatus: 1,
    type: 'OPEX',
    status: 'Create',
    step: 1,
    level: 5,
    createdBy: '582127',
  },
  {
    idStatus: 2,
    type: 'OPEX',
    status: 'Created',
    step: 1,
    function: 'cek report to',
    level: 5,
    createdBy: '582127',
  },
  {
    idStatus: 3,
    type: 'OPEX',
    status: 'Confirm Manager User',
    step: 2,
    level: 4,
    createdBy: '582127',
  },
  {
    idStatus: 4,
    type: 'OPEX',
    status: 'Confirm SM User',
    step: 3,
    level: 3,
    createdBy: '582127',
  },
  {
    idStatus: 5,
    type: 'OPEX',
    status: 'Approve VP User',
    step: 4,
    level: 2,
    function: 'cek type & nominal',
    createdBy: '582127',
  },
  {
    idStatus: 6,
    type: 'OPEX',
    status: 'Review Budget Controller',
    department: 'TAB',
    step: 5,
    level: 5,
    function: 'cek type & nominal',
    createdBy: '582127',
  },
  {
    idStatus: 7,
    type: 'OPEX',
    status: 'Create HPS',
    department: 'TAP',
    step: 5,
    level: 5,
    function: 'cek type & nominal',
    createdBy: '582127',
  },
  {
    idStatus: 8,
    type: 'OPEX',
    status: 'Confirm HPS',
    department: 'TAP',
    step: 6,
    level: 3,
    function: 'cek type & nominal',
    createdBy: '582127',
  },
  {
    idStatus: 9,
    type: 'OPEX',
    status: 'Approve Budget Controller',
    department: 'TAB',
    step: 7,
    level: 3,
    createdBy: '582127',
  },
  {
    idStatus: 10,
    type: 'OPEX',
    status: 'Approve Budget',
    department: 'TA',
    step: 8,
    level: 2,
    createdBy: '582127',
  },
];

export const glAccount = [
  {
    idGlAccount: 1,
    glAccount: 40010001,
    groupDetail: 'Expendable-Material',
    groupGl: 'Material Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 2,
    glAccount: 40012000,
    groupDetail: 'Repairable-Material',
    groupGl: 'Material Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 3,
    glAccount: 40020001,
    groupDetail: 'Rotable parts-Subcont',
    groupGl: 'Subcontract Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 4,
    glAccount: 40014200,
    groupDetail: 'Repairable parts-Subcont',
    groupGl: 'Subcontract Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 5,
    glAccount: 40000000,
    groupDetail: 'Base salary',
    groupGl: 'Staff Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 6,
    glAccount: 40002002,
    groupDetail: 'Honorarium',
    groupGl: 'Staff Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 7,
    glAccount: 40000400,
    groupDetail: 'Travel',
    groupGl: 'Company accommodation',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 8,
    glAccount: 40000403,
    groupDetail: 'Transport',
    groupGl: 'Company accommodation',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 9,
    glAccount: 40030000,
    groupDetail: 'Rotable part',
    groupGl: 'Depreciation & amortisation',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 10,
    glAccount: 40030001,
    groupDetail: 'Amortization',
    groupGl: 'Depreciation & amortisation',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 11,
    glAccount: 40040000,
    groupDetail: 'Maintenance and repair-Hangar',
    groupGl: 'Facility Maintenance expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 12,
    glAccount: 40040005,
    groupDetail: 'Maintenance and repair-Hardware',
    groupGl: 'Facility Maintenance expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 13,
    glAccount: 40041002,
    groupDetail: 'Building-Rental',
    groupGl: 'Rental expenses',
    sap: false,
    active: true,

    createdBy: '582127',
  },
  {
    idGlAccount: 14,
    glAccount: 40041000,
    groupDetail: 'Component-Rental',
    groupGl: 'Rental expenses',
    sap: false,
    active: true,

    createdBy: '582127',
  },
  {
    idGlAccount: 15,
    glAccount: 40043000,
    groupDetail: 'Electricity consumption',
    groupGl: 'Other operating expenses',
    sap: false,
    active: true,

    createdBy: '582127',
  },
  {
    idGlAccount: 16,
    glAccount: 40043006,
    groupDetail: 'Gas',
    groupGl: 'Other operating expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
];

export const costCenters = [
  {
    costCenter: 'ZGMFTA',
    bidang: 'TA',
    dinas: 'TA',
    description: 'Post 1',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAF',
    bidang: 'TAF',
    dinas: 'TA',
    description: 'Post 2',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAR',
    bidang: 'TAR',
    dinas: 'TA',
    description: 'Post 3',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAX',
    bidang: 'TAX',
    dinas: 'TA',
    description: 'Post 4',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTD',
    bidang: 'TD',
    dinas: 'TD',
    description: 'Post 5',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDB',
    bidang: 'TDB',
    dinas: 'TD',
    description: 'Post 6',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDC',
    bidang: 'TDC',
    dinas: 'TD',
    description: 'Post 7',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDI',
    bidang: 'TDI',
    dinas: 'TD',
    description: 'Post 8',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDO',
    bidang: 'TDO',
    dinas: 'TD',
    description: 'Post 9',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDS',
    bidang: 'TDS',
    dinas: 'TD',
    description: 'Post 10',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAP',
    bidang: 'TAP',
    dinas: 'TA',
    description: 'Post 11',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAB',
    bidang: 'TAB',
    dinas: 'TA',
    description: 'Post 12',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAG',
    bidang: 'TAG',
    dinas: 'TA',
    description: 'Post 13',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAM',
    bidang: 'TAM',
    dinas: 'TA',
    description: 'Post 14',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTB',
    bidang: 'TB',
    dinas: 'TB',
    description: 'Post 15',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTBH',
    bidang: 'TBH',
    dinas: 'TB',
    description: 'Post 16',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTBK',
    bidang: 'TBK',
    dinas: 'TB',
    description: 'Post 17',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTBO',
    bidang: 'TBO',
    dinas: 'TB',
    description: 'Post 18',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTBP',
    bidang: 'TBP',
    dinas: 'TB',
    description: 'Post 19',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTBR',
    bidang: 'TBR',
    dinas: 'TB',
    description: 'Post 20',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTBS',
    bidang: 'TBS',
    dinas: 'TB',
    description: 'Post 21',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTBW',
    bidang: 'TBW',
    dinas: 'TB',
    description: 'Post 22',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTC',
    bidang: 'TC',
    dinas: 'TC',
    description: 'Post 23',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTCA',
    bidang: 'TCA',
    dinas: 'TC',
    description: 'Post 24',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTCC',
    bidang: 'TCC',
    dinas: 'TC',
    description: 'Post 25',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTCD',
    bidang: 'TCD',
    dinas: 'TC',
    description: 'Post 26',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTCE',
    bidang: 'TCE',
    dinas: 'TC',
    description: 'Post 27',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTCW',
    bidang: 'TCW',
    dinas: 'TC',
    description: 'Post 28',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTCY',
    bidang: 'TCY',
    dinas: 'TC',
    description: 'Post 29',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTE',
    bidang: 'TE',
    dinas: 'TE',
    description: 'Post 30',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEA',
    bidang: 'TEA',
    dinas: 'TE',
    description: 'Post 31',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEB',
    bidang: 'TEB',
    dinas: 'TE',
    description: 'Post 32',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEJ',
    bidang: 'TEJ',
    dinas: 'TE',
    description: 'Post 33',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEL',
    bidang: 'TEL',
    dinas: 'TE',
    description: 'Post 34',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEM',
    bidang: 'TEM',
    dinas: 'TE',
    description: 'Post 35',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEN',
    bidang: 'TEN',
    dinas: 'TE',
    description: 'Post 36',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEP',
    bidang: 'TEP',
    dinas: 'TE',
    description: 'Post 37',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEQ',
    bidang: 'TEQ',
    dinas: 'TE',
    description: 'Post 38',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTER',
    bidang: 'TER',
    dinas: 'TE',
    description: 'Post 39',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEX',
    bidang: 'TEX',
    dinas: 'TE',
    description: 'Post 40',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTEZ',
    bidang: 'TEZ',
    dinas: 'TE',
    description: 'Post 41',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTF',
    bidang: 'TF',
    dinas: 'TF',
    description: 'Post 42',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTH',
    bidang: 'TH',
    dinas: 'TH',
    description: 'Post 43',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTI',
    bidang: 'TI',
    dinas: 'TI',
    description: 'Post 44',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTJ',
    bidang: 'TJ',
    dinas: 'TJ',
    description: 'Post 45',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTJC',
    bidang: 'TJC',
    dinas: 'TJ',
    description: 'Post 46',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTJH',
    bidang: 'TJH',
    dinas: 'TJ',
    description: 'Post 47',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTJK',
    bidang: 'TJK',
    dinas: 'TJ',
    description: 'Post 48',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTJN',
    bidang: 'TJN',
    dinas: 'TJ',
    description: 'Post 49',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTJO',
    bidang: 'TJO',
    dinas: 'TJ',
    description: 'Post 50',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTJP',
    bidang: 'TJP',
    dinas: 'TJ',
    description: 'Post 51',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTL',
    bidang: 'TL',
    dinas: 'TL',
    description: 'Post 52',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLB',
    bidang: 'TLB',
    dinas: 'TL',
    description: 'Post 53',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLC',
    bidang: 'TLC',
    dinas: 'TL',
    description: 'Post 54',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLD',
    bidang: 'TLD',
    dinas: 'TL',
    description: 'Post 55',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLF',
    bidang: 'TLF',
    dinas: 'TL',
    description: 'Post 56',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLG',
    bidang: 'TLG',
    dinas: 'TL',
    description: 'Post 57',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLK',
    bidang: 'TLK',
    dinas: 'TL',
    description: 'Post 58',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLM',
    bidang: 'TLM',
    dinas: 'TL',
    description: 'Post 59',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLN',
    bidang: 'TLN',
    dinas: 'TL',
    description: 'Post 60',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLP',
    bidang: 'TLP',
    dinas: 'TL',
    description: 'Post 61',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTLS',
    bidang: 'TLS',
    dinas: 'TL',
    description: 'Post 62',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTM',
    bidang: 'TM',
    dinas: 'TM',
    description: 'Post 63',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTMC',
    bidang: 'TMC',
    dinas: 'TM',
    description: 'Post 64',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTME',
    bidang: 'TME',
    dinas: 'TM',
    description: 'Post 65',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTML',
    bidang: 'TML',
    dinas: 'TM',
    description: 'Post 66',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTMO',
    bidang: 'TMO',
    dinas: 'TM',
    description: 'Post 67',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTMS',
    bidang: 'TMS',
    dinas: 'TM',
    description: 'Post 68',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTMW',
    bidang: 'TMW',
    dinas: 'TM',
    description: 'Post 69',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTN',
    bidang: 'TN',
    dinas: 'TN',
    description: 'Post 70',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTP',
    bidang: 'TP',
    dinas: 'TP',
    description: 'Post 71',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTQ',
    bidang: 'TQ',
    dinas: 'TQ',
    description: 'Post 72',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTR',
    bidang: 'TR',
    dinas: 'TR',
    description: 'Post 73',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTRP',
    bidang: 'TRP',
    dinas: 'TR',
    description: 'Post 74',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTRS',
    bidang: 'TRS',
    dinas: 'TR',
    description: 'Post 75',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTS',
    bidang: 'TS',
    dinas: 'TS',
    description: 'Post 76',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTU',
    bidang: 'TU',
    dinas: 'TU',
    description: 'Post 77',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTV',
    bidang: 'TV',
    dinas: 'TV',
    description: 'Post 78',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTVE',
    bidang: 'TVE',
    dinas: 'TV',
    description: 'Post 79',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTVP',
    bidang: 'TVP',
    dinas: 'TV',
    description: 'Post 80',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTVU',
    bidang: 'TVU',
    dinas: 'TV',
    description: 'Post 81',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTX',
    bidang: 'TX',
    dinas: 'TX',
    description: 'Post 82',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTY',
    bidang: 'TY',
    dinas: 'TY',
    description: 'Post 83',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTZ',
    bidang: 'TZ',
    dinas: 'TZ',
    description: 'Post 84',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTZG',
    bidang: 'TZG',
    dinas: 'TZ',
    description: 'Post 85',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTZP',
    bidang: 'TZP',
    dinas: 'TZ',
    description: 'Post 86',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
];
